name: Deploy helm App


on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      replica:
        description: 'Number of Replicas'
        required: true
        default: '2'
      reason:
        description: 'Reason for Deployment'
        required: false
        default: 'Routine update'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to your K8s cluster (Generic example for AWS/GCP/Azure)
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml
          pwd
          export KUBECONFIG=$PWD/kubeconfig.yaml

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest' # Or a specific version like 'v3.12.0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify Cluster Connection
        id: verify_cluster
        run: kubectl cluster-info;pwd;
        env:
          # This variable tells Helm/Kubectl where to look
          KUBECONFIG: ./kubeconfig.yaml

      - name: Create Dynamic Overrides
        env:
          # This variable tells Helm/Kubectl where to look
          KUBECONFIG: ./kubeconfig.yaml
        if: success() && steps.verify_cluster.outcome == 'success'
        run: |
          cat <<EOF > values-user-overrides.yaml
          replicaCount: "${{ github.event.inputs.replica }}"
          image:
            repository: nginx
            pullPolicy: IfNotPresent
            # Overrides the image tag whose default is the chart appVersion.
            tag: "latest"
          nameOverride: "abhishek-helm-deployment-${{github.run_number}}"
          fullnameOverride: "abhishek-helm-deployment-${{github.run_number}}"
          customAnnotations:
            deployed-by: "${{ github.actor }}"
            reason: "${{ github.event.inputs.reason }}"
          EOF
          pwd;ls -la;cat values-user-overrides.yaml


      - name: Deploy to Kubernetes
        env:
          # This variable tells Helm/Kubectl where to look
          KUBECONFIG: ./kubeconfig.yaml        
        run: |
          pwd;ls -la;
          # Use the -f flag to point to the environment-specific values file
          helm upgrade --install helm-app-${{ github.event.inputs.environment }} ./app-deploy \
            --namespace ${{ github.event.inputs.environment }} \
            --create-namespace \
            -f ./values-user-overrides.yaml 