name: Deploy helm App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod
      replica:
        description: 'Number of Replicas'
        required: true
        default: '2'
      reason:
        description: 'Reason for Deployment'
        required: false
        default: 'Routine update'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to your K8s cluster (Generic example for AWS/GCP/Azure)
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG_DATA }}" > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Verify Cluster Connection
        id: verify_cluster
        run: kubectl cluster-info

      - name: Create Dynamic Overrides
        if: success() && steps.verify_cluster.outcome == 'success'
        run: |
          cat <<EOF > user-overrides.yaml
          replicaCount: "${{ github.event.inputs.replica }}"
          image:
            repository: nginx
            pullPolicy: IfNotPresent
            # Overrides the image tag whose default is the chart appVersion.
            tag: "latest"
          nameOverride: "abhishek-helm-deployment"
          fullnameOverride: "abhishek-helm-deployment"
          customAnnotations:
            deployed-by: "${{ github.actor }}"
            reason: "${{ github.event.inputs.reason }}"
          EOF


      - name: Deploy to Kubernetes
        run: |
          # Use the -f flag to point to the environment-specific values file
          helm upgrade --install helm-app-${{ github.event.inputs.environment }} ./app-deploy \
            --namespace ${{ github.event.inputs.environment }} \
            --create-namespace \
            -f ./ace-app-chart/values-user-overrides.yaml \
            --set image.tag=${{ github.sha }}